name: Image build on event

on: [push]


jobs:
  build:

    runs-on: ubuntu-22.04
    if: "github.event_name == 'push' && !contains(github.event.head_commit.modified, 'last.releases')"      
    strategy:
      fail-fast: false # Don't fail all if any of the jobs is failing
      matrix:
        TESTING: [release]
        TARGET: [x20] # <-- Add targets here!


    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        overprovision-lvm: 'true'
    - name: Setup env
      run: |

        echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
        echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
    
    
    ### ONLY THIS RELEVANT FOR BUILDING ###
    - uses: actions/checkout@v3
    - name: update
      run: sudo apt-get update
    - name: fix ci's
      run: sudo apt-mark hold grub-efi-amd64-signed
    - name: upgrade
      run: sudo apt-get upgrade -y
    - name: dep
      run: sudo apt-get install -y unzip tree curl git qemu qemu-user-static binfmt-support
    - name: debug
      run: ls -a
    - name: configure
      run: sudo bash build.sh ${{ matrix.TARGET }} ${{ matrix.TESTING }}
    - name: debug
      run: tree
    